"""自动提取的 card_transaction 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="card_transaction", description="")
class CardTransaction:
    COLUMNS = {
        "id_no": {"type": "bigint"},
        "account_id": {"type": "uuid"},
        "card_id": {"type": "uuid"},
        "card_channel": {"type": "varchar", "description": "卡渠道"},
        "origin_amount": {"type": "numeric", "description": "原始金额"},
        "origin_currency": {"type": "varchar", "description": "原始交易币种"},
        "settle_amount": {"type": "numeric", "description": "交易金额"},
        "total_amount": {"type": "numeric", "description": "当前订单总消费金额"},
        "fee": {"type": "numeric", "description": "交易手续费"},
        "type": {"type": "varchar", "description": "交易类型"},
        "reason_code": {"type": "integer", "description": "原因码"},
        "status": {"type": "varchar", "description": "交易状态"},
        "process_status": {"type": "varchar", "description": "交易状态"},
        "currency": {"type": "varchar", "description": "币种"},
        "local_trx_amount": {"type": "numeric", "description": "本地交易金额"},
        "local_trx_currency": {"type": "varchar", "description": "本地交易币种"},
        "order_num": {"type": "text", "description": "订单号"},
        "transaction_id": {"type": "uuid", "description": "交易表ID"},
        "budget_id": {"type": "uuid", "description": "卡预算ID"},
        "source_id": {"type": "varchar", "description": "三方交易表ID"},
        "trace_id": {"type": "varchar", "description": "订单跟踪ID，如授权交易ID"},
        "detail": {"type": "varchar", "description": "交易描述"},
        "channel_complete_at": {"type": "timestamptz", "description": "三方订单完成时间"},
        "trade_tag": {"type": "varchar", "description": "交易标签"},
        "raw": {"type": "json", "description": "缓存数据"},
        "is_cleared": {"type": "text", "description": "是否清算"},
        "scene_id": {"type": "uuid", "description": "场景ID"},
        "call_id": {"type": "varchar", "description": "API客户的请求ID"},
        "customer_notes": {"type": "varchar", "description": "客户备注(Notes)"},
        "transaction_at": {"type": "timestamptz", "description": "订单创建时间"},
        "complete_at": {"type": "timestamptz", "description": "订单完成时间"},
        "batch_id": {"type": "varchar"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
