"""自动提取的 cdd_business 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="cdd_business", description="CustomerDueDiligence business-info")
class CddBusiness:
    COLUMNS = {
        "account_id": {"type": "uuid"},
        "kyc_id": {"type": "uuid"},
        "registration_region": {"type": "varchar", "description": "注册国家/地区"},
        "business_place_type": {"type": "varchar", "description": "经营场所类型"},
        "business_name": {"type": "varchar", "description": "企业名称"},
        "business_name_en": {"type": "varchar", "description": "企业英文名称"},
        "business_type": {"type": "varchar", "nullable": False, "description": "企业类型"},
        "business_size": {"type": "varchar", "description": "企业规模"},
        "business_id": {"type": "varchar", "description": "统一社会信用代码"},
        "business_registration_date": {"type": "varchar", "description": "注册日期,格式：YYYY-MM-DD"},
        "established_date": {"type": "varchar", "description": "证件发行日期，格式：YYYY-MM-DD"},
        "attachment": {"type": "json", "description": "企业附件"},
        "contact_info": {"type": "jsonb", "description": "联络人信息"},
        "product_binding_info": {"type": "jsonb", "description": "产品信息"},
        "ownership_structure": {"type": "varchar", "description": "所有权结构"},
        "has_bearer_shares": {"type": "boolean", "description": "是否发行不记名股票"},
        "tax_structure": {"type": "varchar", "description": "税务结构"},
        "tax_countries": {"type": "jsonb", "description": "税务所在国家列表, 示例：["},
        "directors_info": {"type": "jsonb", "description": "公司董事&自然人大股东/高级管理人员信息"},
        "counterparty_countries": {"type": "jsonb", "description": "交易对手-买方/卖方所在主要国家"},
        "main_business": {"type": "varchar", "description": "主营业务"},
        "industry_category": {"type": "varchar", "description": "行业大类"},
        "website": {"type": "varchar", "description": "公司网站"},
        "website_type": {"type": "varchar", "description": "公司网站类型"},
        "account_manager": {"type": "varchar", "description": "账户经理"},
        "estimated_monthly_transaction_amount": {"type": "varchar", "description": "预估月均交易额"},
        "funding_source": {"type": "jsonb", "description": "入金来源"},
        "withdrawal_purpose": {"type": "jsonb", "description": "出金用途"},
        "business_registration_number": {"type": "varchar", "description": "商业登记号码(BR号)"},
        "register_capital": {"type": "numeric", "description": "注册资本(USD)"},
        "aml_info": {"type": "jsonb", "description": "aml 信息"},
        "is_same_address": {"type": "boolean", "description": "是否相同地址（注册地址和经营地址）"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
