"""自动提取的 crypto_transaction 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="crypto_transaction", description="")
class CryptoTransaction:
    COLUMNS = {
        "id_no": {"type": "bigint"},
        "account_id": {"type": "varchar", "description": "账户id"},
        "balance_id": {"type": "varchar"},
        "action": {"type": "varchar", "description": "交易动作"},
        "business_type": {"type": "varchar", "description": "业务类型"},
        "currency": {"type": "text"},
        "address": {"type": "varchar", "description": "地址，如果是充值则为打款来缘方地址"},
        "origin_amount": {"type": "numeric", "description": "源交易金额"},
        "origin_currency": {"type": "varchar", "description": "原始交易币种"},
        "amount": {"type": "numeric", "description": "交易金额"},
        "fee": {"type": "numeric", "description": "交易手续费"},
        "cross_chain_fee": {"type": "numeric", "description": "跨链手续费"},
        "status": {"type": "text"},
        "process_status": {"type": "varchar", "description": "流转状态"},
        "chain_status": {"type": "varchar", "description": "链上交易状态"},
        "trade_id": {"type": "varchar", "description": "跟踪id"},
        "payee_id": {"type": "varchar", "description": "收款人id(如果是入金，则对应的是crypto_addresses的ID)"},
        "payee_walled_id": {"type": "varchar", "description": "收款钱包id"},
        "wallet_id": {"type": "varchar"},
        "transaction_id": {"type": "varchar"},
        "transaction_time": {"type": "timestamptz"},
        "rate": {"type": "numeric"},
        "deal_rate": {"type": "numeric"},
        "quote_currency": {"type": "varchar"},
        "quote_amount": {"type": "numeric"},
        "hidden": {"type": "boolean"},
        "sender_type": {"type": "varchar"},
        "sender_name": {"type": "varchar"},
        "recipient_type": {"type": "varchar"},
        "recipient_name": {"type": "varchar"},
        "close_time": {"type": "timestamptz"},
        "raw_data": {"type": "varchar"},
        "chain_tx_id": {"type": "varchar"},
        "related_id": {"type": "varchar"},
        "customer_notes": {"type": "varchar", "description": "客户备注(Notes)"},
        "call_id": {"type": "varchar"},
        "channel": {"type": "varchar", "description": "加密钱包渠道"},
        "reference": {"type": "varchar", "description": "附言"},
        "transaction_at": {"type": "timestamptz", "description": "订单创建时间"},
        "complete_at": {"type": "timestamptz", "description": "订单完成时间"},
        "batch_id": {"type": "varchar"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
