"""自动提取的 pay_transaction 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="pay_transaction", description="")
class PayTransaction:
    COLUMNS = {
        "id_no": {"type": "bigint"},
        "account_id": {"type": "uuid", "description": "账户ID"},
        "amount": {"type": "numeric", "description": "订单金额（支付或退款）"},
        "fee": {"type": "numeric", "description": "交易手续费"},
        "total_amount": {"type": "numeric", "description": "当前订单总消费金额"},
        "usd_rate": {"type": "numeric", "description": "订单汇率"},
        "usd_amount": {"type": "numeric", "description": "订单美元金额"},
        "usd_fee_amount": {"type": "numeric", "description": "订单美元手续费"},
        "currency": {"type": "varchar", "description": "订单创建选定币种"},
        "pay_currency": {"type": "varchar", "description": "实际支付币种"},
        "status": {"type": "varchar", "description": "订单标准状态"},
        "process_status": {"type": "varchar", "description": "其他状态（后续扩展）"},
        "settle_status": {"type": "varchar", "description": "订单结算状态"},
        "pay_channel": {"type": "varchar", "description": "支付渠道类型"},
        "type": {"type": "varchar", "description": "订单类型：支付订单，退款订单"},
        "origin_pay_order_id": {"type": "varchar", "description": "关联的原始订单(如：退款时,关联的支付订单ID)"},
        "call_id": {"type": "varchar", "description": "call_id"},
        "balance_id": {"type": "uuid", "description": "关联的余额ID"},
        "transaction_id": {"type": "uuid", "description": "关联的交易ID"},
        "source_id": {"type": "varchar", "description": "来源ID"},
        "success_url": {"type": "varchar", "description": "成功回调地址"},
        "failure_url": {"type": "varchar", "description": "失败回调地址"},
        "extra_data": {"type": "jsonb", "description": "额外数据"},
        "raw_data": {"type": "jsonb", "description": "原始数据"},
        "pay_channel_currency_id": {"type": "uuid", "description": "关联的支付渠道币种ID"},
        "payer": {"type": "varchar", "description": "支付者(如：链的钱包地址、gate的client_id)"},
        "wait_amount_on_chain": {"type": "varchar", "description": "等待链上确认的金额"},
        "done_amount_on_chain": {"type": "varchar", "description": "链上已确认的金额"},
        "address": {"type": "varchar", "description": "预收款地址"},
        "receive_address": {"type": "varchar", "description": "实际收款地址"},
        "pay_type": {"type": "varchar", "description": "支付方式"},
        "expire_time": {"type": "bigint", "description": "支付过期时间"},
        "customer_notes": {"type": "varchar", "description": "客户备注(Notes)"},
        "transaction_at": {"type": "timestamptz", "description": "订单创建时间"},
        "completed_at": {"type": "timestamptz", "description": "订单完成时间"},
        "batch_id": {"type": "varchar"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
