"""自动提取的 pay_transaction_refund 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="pay_transaction_refund", description="")
class PayTransactionRefund:
    COLUMNS = {
        "id_no": {"type": "bigint", "description": "退款单雪花ID"},
        "chain_pay_transaction_id": {"type": "uuid", "description": "chain_pay_transaction.id"},
        "pay_transaction_id": {"type": "uuid", "description": "pay_transaction.id"},
        "account_id": {"type": "uuid", "description": "账户ID"},
        "pay_transaction_exception_id": {"type": "uuid", "description": "pay_transaction_exception.id"},
        "pay_sub_transaction_id": {"type": "uuid", "description": "pay_sub_transaction.id"},
        "pay_id_no": {"type": "bigint", "description": "pay_transaction.id_no"},
        "source_id": {"type": "varchar", "description": "Gate prepayId/source_id"},
        "original_tx_hashes": {"type": "jsonb", "description": "原链上入金hash列表"},
        "refund_scene": {"type": "varchar", "description": "退款场景"},
        "refund_amount_type": {"type": "varchar", "description": "退款金额类型"},
        "refund_request_id": {"type": "varchar", "description": "商户退款请求ID"},
        "source_refund_id": {"type": "varchar", "description": "Gate退款单ID"},
        "refund_method": {"type": "varchar", "description": "退款方式"},
        "refund_channel": {"type": "varchar", "description": "退款渠道"},
        "status": {"type": "varchar", "description": "退款状态"},
        "arrived_amount": {"type": "numeric", "description": "实际到账金额"},
        "refund_fee_amount": {"type": "numeric", "description": "value = 链退款手续费 + 收款金额手续费（按创建订单逻辑计算）"},
        "chain_refund_fee_amount": {"type": "numeric", "description": "链退款手续费"},
        "order_fee_amount": {"type": "numeric", "description": "收款金额手续费（按创建订单逻辑计算）"},
        "refund_amount": {"type": "numeric", "description": "退款金额，未扣除手续费前的金额"},
        "refund_currency": {"type": "varchar", "description": "退款币种"},
        "refund_chain": {"type": "varchar", "description": "指定退款链"},
        "refund_address": {"type": "varchar", "description": "指定退款地址"},
        "refund_to_gate_uid": {"type": "varchar", "description": "Gate UID退款时使用"},
        "refund_bear_type": {"type": "varchar", "description": "手续费承担方"},
        "settle_status": {"type": "varchar", "description": "本地结算状态"},
        "transaction_id": {"type": "uuid", "description": "本地余额交易ID"},
        "settle_balance_id": {"type": "uuid", "description": "本地结算扣款余额ID"},
        "settle_principal_amount": {"type": "numeric", "description": "本地结算本金扣款金额"},
        "settle_fee_amount": {"type": "numeric", "description": "本地结算手续费扣款金额"},
        "settled_at": {"type": "timestamptz", "description": "本地结算完成时间"},
        "refund_tx_hash": {"type": "varchar", "description": "退款hash"},
        "fail_reason": {"type": "text", "description": "失败原因"},
        "order_snapshot": {"type": "jsonb", "description": "Gate订单查询快照"},
        "request_data": {"type": "jsonb", "description": "退款请求"},
        "response_data": {"type": "jsonb", "description": "退款响应"},
        "refund_detail": {"type": "jsonb", "description": "退款详情"},
        "requested_at": {"type": "timestamptz", "description": "请求退款时间"},
        "refunded_at": {"type": "timestamptz", "description": "退款完成时间"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
