"""自动提取的 payout_transaction 表 schema。"""
from finance_agent.metadata.table_registry import register_table


@register_table(name="payout_transaction", description="")
class PayoutTransaction:
    COLUMNS = {
        "id_no": {"type": "bigint", "nullable": False, "description": "订单号"},
        "account_id": {"type": "uuid", "nullable": False, "description": "账户ID"},
        "payee_id": {"type": "uuid", "nullable": False, "description": "受益人ID"},
        "receive_type": {"type": "varchar", "description": "付款方式"},
        "payee_modifiable": {"type": "boolean", "description": "收款人是否可被修改"},
        "amount": {"type": "numeric", "description": "交易金额"},
        "payer_currency": {"type": "varchar", "description": "付款币种（扣款/余额币种，下单时快照）"},
        "payee_currency": {"type": "varchar", "description": "收款币种（受益人到账币种，与 amount 一致，下单时快照）"},
        "business_trx_id": {"type": "uuid", "nullable": False, "description": "业务方的订单ID;va/cw"},
        "business_source": {"type": "varchar", "nullable": False, "description": "业务来源"},
        "channel_trx_id": {"type": "varchar", "description": "渠道测订单ID"},
        "payout_channel": {"type": "varchar", "description": "付款渠道"},
        "review_time": {"type": "timestamptz", "description": "审核时间"},
        "complete_at": {"type": "timestamptz", "description": "订单完成时间"},
        "status": {"type": "varchar", "description": "交易状态"},
        "process_status": {"type": "varchar", "description": "流转态"},
        "progress_status": {"type": "varchar", "description": "付款进度状态"},
        "channel_status": {"type": "varchar", "description": "最新渠道原始状态"},
        "comment": {"type": "varchar", "description": "转账附言"},
        "purpose": {"type": "varchar", "description": "渠道的付款目的代码"},
        "internal_purpose": {"type": "varchar", "description": "内部付款目的代码"},
        "raw": {"type": "json", "description": "原始json"},
        "refund_id": {"type": "varchar", "description": "退款ID"},
        "refund_status": {"type": "varchar", "description": "退款状态"},
        "refund_id_no": {"type": "varchar", "description": "业务方的退款订单号（va=va_refund.id_no，cw=crypto system_refund.id_no，ca=account system_refund.id_no）"},
        "channel_payee_id": {"type": "varchar", "description": "渠道存储收款方返回的记录编号"},
        "pobo": {"type": "boolean", "description": "是否以用户名义出款 有值代表是"},
        "cost_borne": {"type": "varchar", "description": "费用承担方式：SHA-非全额到账、OUR-全额到账"},
        "base_fee": {"type": "numeric", "description": "基础手续费"},
        "pobo_fee": {"type": "numeric", "description": "实名付款手续费"},
        "our_fee": {"type": "numeric", "description": "足额到账手续费"},
        "payer_fee": {"type": "numeric", "description": "定制付款人手续费(付款货币)"},
        "rate": {"type": "numeric", "description": "成交汇率"},
        "quote_id": {"type": "varchar", "description": "外汇询价id"},
        "fx_id": {"type": "varchar", "description": "外汇对客单号"},
        "fx_order_status": {"type": "varchar", "description": "外汇订单状态"},
        "call_id": {"type": "varchar", "description": "API Caller ID (unique within the same business)"},
        "customer_notes": {"type": "varchar", "description": "客户备注(Notes)"},
        "aml_info": {"type": "jsonb", "description": "aml 信息"},
        "id": {"type": "uuid", "nullable": False, "description": "主键"},
        "remarks": {"type": "text"},
        "created_at": {"type": "timestamptz"},
        "update_at": {"type": "timestamptz"},
        "delete_at": {"type": "timestamptz"},
        "version": {"type": "integer", "nullable": False},
    }
